services:
  - type: web
    name: chatapp
    env: python
    plan: free
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p $PORT chat.asgi:application"
    runtime: python3
    region: frankfurt
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chat.settings
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: REDIS_URL
        sync: false
